#-------------------------------
# General Site Settings

title: El Guendouz Mohamed | Data Engineer Cloud
description: Expert en ingénierie et architecture des données, je possède une solide expertise en plateformes cloud et technologies Big Data.  Je conçois des solutions data innovantes et performantes, incluant des architectures scalables et robustes, pour répondre à vos enjeux les plus complexes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mohamedelguendouz.github.io" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
author-name:   Mohamed El Guendouz
author-avatar: profil.jpeg


#-------------------------------
# Contact links
facebook:  https://facebook.com/ # Add your Facebook handle
twitter:   https://twitter.com/ # Add your Facebook handle
instagram: https://www.instagram.com/ # Add your Facebook handle
pinterest: https://www.pinterest.com/ # Add your Facebook handle
linkedin:  https://www.linkedin.com/in/melg-0686aa151/
#-------------------------------
# Comment Section (Disqus)
disqus-identifier: El Guendouz Mohamed # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Instagram Feed
instafeed: false # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: https://sibforms.com/serve/MUIFACMZeK_FUEqqhr3i6-M57WS0YOsBu6cbl5_yH0oUiD0fGFSqBNyBm1nA7tE2NSyEC6eUxf43L4MIG4dda5rpDJW0YncnjZ7WJR63qHJfAojPqcKpf2d7fa1vU_lolqkaJL10slY4gsfL76Ejve43JFH7q6sWHj0rL4qYx1Qn1qBTuqWSbuqxcK1EVJiT1LIdfp3MVdx2Pr6m
# Pas utilisé
#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/